"""empty message

Revision ID: d552e639b582
Revises: c500a1b40e3f
Create Date: 2020-01-11 19:59:25.971990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd552e639b582'
down_revision = 'c500a1b40e3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('surveys', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'surveys', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'surveys', type_='foreignkey')
    op.drop_column('surveys', 'creator_id')
    op.drop_table('users')
    # ### end Alembic commands ###
